MODEL:
  TYPE: swin
  NAME: gfmaerial_pretrain_swin_teacher
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
    TEACHER_WINDOW_SIZE: 7 #7
DATA:
  IMG_SIZE: 384
  TEACHER_IMG_SIZE: 224 #224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  #DATA_TRAIN_PATH: "/home/embedding/Data_Center/Vera/full_train.lmdb"
  #DATA_TRAIN_PATH: "/home/embedding/Data_Center/Vera/GFM_aerial_datasets/train/full_train_smaller.lmdb"
  #DATA_VALI_PATH_TEMP_IND: "/home/embedding/Data_Center/Vera/GFM_aerial_datasets/vali/vali_temp_ind_HH_with_test_swap.lmdb"
  #DATA_VALI_PATH_SPA_IND: "/home/embedding/Data_Center/Vera/GFM_aerial_datasets/vali/vali_spatially_ind.lmdb"
  DATA_TRAIN_PATH: "/nne_mount/Vera/Data/Test/test_spati_temp_ind_noHH_with_vali_samples.lmdb"
  DATA_VALI_PATH_TEMP_IND: "/nne_mount/Vera/Data/Test/test_spati_temp_ind_noHH_with_vali_samples.lmdb"
  DATA_VALI_PATH_SPA_IND: "/nne_mount/Vera/Data/Test/test_spati_temp_ind_noHH_with_vali_samples.lmdb"
  DATA_VALI_PATH_TEMP_SPA_IND: "/nne_mount/Vera/Data/Test/test_spati_temp_ind_noHH_with_vali_samples.lmdb"
TRAIN:
  EPOCHS: 4 #100
  WARMUP_EPOCHS: 1 #10
  BASE_LR: 2e-4
  WARMUP_LR: 1e-6
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.05
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: gfm_aerial_swin_teacher_22k