MODEL:
  TYPE: swin
  NAME: gfmaerial_pretrain
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6
    TEACHER_WINDOW_SIZE: 6 #for gfm, 7 for swin
    IN_CHANS: 4 #for gfmaerial, 3 for gfm
    IN_CHANS_TEACHER: 3
DATA:
  IMG_SIZE: 192 #size of the encoder, not the data
  TEACHER_IMG_SIZE: 192 #for gfm, 224 for swin
  MASK_PATCH_SIZE: 32 #number of masked-out areas per image
  MASK_RATIO: 0.6 #masked % of image range [0,1]
  DATA_TRAIN_PATH: "/home/malik/Projects/GFM_aerial/test_tiles.lmdb"
  DATA_VALI_PATH_TEMP_IND: "/home/malik/Projects/GFM_aerial/test_tiles.lmdb"
  DATA_VALI_PATH_SPA_IND: "/home/malik/Projects/GFM_aerial/test_tiles.lmdb"
  DATA_VALI_PATH_TEMP_SPA_IND: "/home/malik/Projects/GFM_aerial/test_tiles.lmdb"
  OUTPUT_LMDB: None #save reconstructed images when testing
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  BASE_LR: 2e-4
  WARMUP_LR: 1e-6
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.05
PRINT_FREQ: 100 #print stats after that many batches
SAVE_FREQ: 5 #save checkpoint at least after that many epochs. If model improved checkpoint is saved either way
TAG: gfm_aerial_pretrain