MODEL:
  TYPE: swin
  NAME: gfmaerial_pretrain
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 6 #6
    TEACHER_WINDOW_SIZE: 6
DATA:
  IMG_SIZE: 384 #768
  TEACHER_IMG_SIZE: 192
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
  DATA_TRAIN_PATH: "/home/embedding/Data_Center/Vera/full_train.lmdb"
  DATA_VALI_PATH_TEMP_IND: "/home/embedding/Data_Center/DataHouse/Gfm_aerial/datasets_boxes/new_temp_ind/test_temp_ind_noHH_with_vali_samples.lmdb"
  DATA_VALI_PATH_SPA_IND: "/home/embedding/Data_Center/DataHouse/Gfm_aerial/datasets_boxes/vali/vali_spati_temp_ind_hist.lmdb"
  DATA_VALI_PATH_TEMP_SPA_IND: "/home/embedding/Data_Center/DataHouse/Gfm_aerial/datasets_boxes/new_temp_ind/test_spati_temp_ind_noHH_with_vali_samples.lmdb"
TRAIN:
  EPOCHS: 3
  WARMUP_EPOCHS: 1
  BASE_LR: 2e-4
  WARMUP_LR: 1e-6
  MIN_LR: 1e-5
  WEIGHT_DECAY: 0.05
PRINT_FREQ: 100
SAVE_FREQ: 5
TAG: simmim_pretrain__swin_base__img192_window6__100ep